/* ─────────────────────────────────────────────
   HIKARI CARE — lang.js
   Bilingual: Japanese (default) + English
───────────────────────────────────────────── */

const LANG = {

  /* ── JAPANESE (Default) ── */
  ja: {
    /* Util bar */
    utilTel:     "📞 0120-000-000",
    utilHours:   "受付時間 9:00〜17:00（月〜土）",
    langToggle:  "EN",

    /* Navigation */
    navHome:     "ホーム",
    navService:  "サービス",
    navFacility: "施設を探す",
    navRecruit:  "採用情報",
    navContact:  "お問い合わせ",

    /* Header CTA */
    telLabel:    "お電話でのご相談",
    btnContact:  "お問い合わせ",

    /* Mobile menu */
    mobileClose: "閉じる",

    /* ── INDEX ── */

    /* Hero */
    heroBadge:    "Care With Heart — 心のこもった介護",
    heroTitle1:   "心のこもった介護を",
    heroTitle2:   "あなたのそばに。",
    heroDesc:     "ひかり苑は、ご入居者様・ご利用者様が\nその人らしく、笑顔で過ごせるよう\n温かく支援し続けます。",
    heroBtnFind:  "施設を探す",
    heroBtnSvc:   "サービスを見る",

    /* Gallery */
    galleryEn:    "DAILY LIFE",
    galleryTitle: "スタッフと利用者様の日常",
    galleryDesc:  "笑顔あふれる日常の一コマをご紹介します。",
    galCap1:      "レクリエーション活動",
    galCap2:      "季節のお花見",
    galCap3:      "リハビリ・体操",
    galCap4:      "食事タイム",
    galCap5:      "中庭でのひととき",

    /* Features */
    featEn:       "FEATURE",
    featTitle:    "ひかり苑の3つの特徴",
    featDesc:     "すべてのご利用者様に、安心・安全・温もりのある介護をお届けします。",
    feat1Title:   "専門スタッフによる\n安心・安全のケア",
    feat1Desc:    "介護福祉士をはじめとする有資格者が24時間体制でサポート。緊急時も迅速に対応できる体制を整えています。医療機関との連携もしっかりと行っています。",
    feat2Title:   "居心地のよい\n温かい環境づくり",
    feat2Desc:    "自宅のようにくつろげる空間設計。季節感を大切にしたインテリアと、緑豊かな中庭・庭園で、ゆったりとした日常をお過ごしいただけます。",
    feat3Title:   "その人らしさを支える\n笑顔のサポート",
    feat3Desc:    "趣味・生きがいを大切にし、一人ひとりに合った個別ケアプランを作成。音楽・手工芸・季節行事など多彩なレクリエーションで笑顔の毎日をともに作ります。",

    /* Services preview */
    svcEn:        "SERVICE",
    svcTitle:     "サービス紹介",
    svcDesc:      "ご入居者様・ご利用者様のニーズに合わせた多様なサービスをご用意しています。",
    svc1Tag:      "RESIDENTIAL CARE",
    svc1Title:    "有料老人ホーム",
    svc1Desc:     "24時間365日、専任スタッフが常駐する安心の住まい。食事・入浴・排泄などの介助から、リハビリ・レクリエーション活動まで充実したサポートをご提供します。一人ひとりのペースを大切にした、丁寧な個別ケアが自慢です。",
    svc1p1:       "24時間専任スタッフ常駐、緊急時も迅速対応",
    svc1p2:       "栄養士監修の日替わり食事（選択メニューあり）",
    svc1p3:       "個別ケアプランに基づく丁寧な生活支援",
    svc1Btn:      "詳しく見る →",
    svc2Tag:      "DAY SERVICE",
    svc2Title:    "デイサービス",
    svc2Desc:     "自宅から通いながら、日中の活動・機能訓練・入浴などのサービスをご利用いただけます。ご家族の介護負担を軽減しながら、在宅生活をしっかり支えます。仲間との交流で生活に活気とリズムを。",
    svc2p1:       "送迎サービスで自宅から安心通所",
    svc2p2:       "機能訓練・レクリエーションで生活機能の維持向上",
    svc2p3:       "入浴・食事・排泄介助をワンストップ提供",
    svc2Btn:      "詳しく見る →",

    /* About */
    aboutEn:      "ABOUT US",
    aboutTitle:   "ご入居者様を\n家族のように。",
    aboutDesc:    "ひかり苑が大切にしているのは、ただ「介護する」ことではありません。その方の人生そのものに寄り添い、生きがいをともに見つけることです。",
    phil1Title:   "その人らしい生活を守る",
    phil1Desc:    "長年培ってきた生活習慣や個性を尊重し、自分らしく過ごせる環境をご提供します。",
    phil2Title:   "家族との絆を大切に",
    phil2Desc:    "ご家族と常に連携し、いつでも安心して面会・参加できる開かれた施設を目指します。",
    phil3Title:   "継続的な質の向上",
    phil3Desc:    "スタッフ研修・外部評価を積極的に取り入れ、ケアの質を常に高め続けます。",

    /* News */
    newsEn:        "NEWS",
    newsTitle:     "お知らせ・活動報告",
    newsDesc:      "施設からの最新のお知らせや、日々の活動の様子をお届けします。",
    newsCatEvent:  "イベント",
    newsCatRecruit:"採用",
    newsCatNews:   "お知らせ",
    news1Date:     "2026.04.20",
    news1Title:    "春のお花見イベントを開催しました",
    news1Excerpt:  "近くの公園で入居者の皆様と桜を楽しみました。笑顔がたくさん溢れた一日でした。",
    news2Date:     "2026.04.05",
    news2Title:    "介護スタッフ募集中（未経験歓迎）",
    news2Excerpt:  "正社員・パート問わず募集中です。資格取得支援あり。まずはお気軽にご連絡ください。",
    news3Date:     "2026.03.15",
    news3Title:    "東京新宿施設 リニューアルオープンのお知らせ",
    news3Excerpt:  "共用スペースと居室を全面リニューアル。より快適な環境でお迎えします。",
    newsMoreBtn:   "お知らせ一覧を見る →",

    /* CTA */
    ctaEn:        "FIND CARE",
    ctaTitle:     "お近くのひかり苑を\n探してみましょう",
    ctaDesc:      "地域・サービス種別から、ご希望に合った施設をすぐに見つけられます。見学・体験入居のご相談もお気軽にどうぞ。",
    ctaBtn1:      "施設を探す",
    ctaBtn2:      "資料請求・見学のご相談",

    /* Recruitment teaser */
    recruitTag:   "RECRUITMENT",
    recruitTitle: "介護スタッフ募集中",
    recruitDesc:  "ひかり苑では、利用者様の笑顔のために共に働くスタッフを積極募集しています。未経験歓迎・資格取得支援あり。あなたの「誰かを支えたい」という気持ちを全力でバックアップします。",
    recruitBtn:   "採用情報を見る →",

    /* Footer */
    footDesc:      "心のこもった介護で、ご入居者様・ご利用者様の毎日に笑顔と安心をお届けします。",
    footMenuTitle: "メニュー",
    footMenu1:     "ホーム",
    footMenu2:     "サービス紹介",
    footMenu3:     "施設を探す",
    footMenu4:     "採用情報",
    footMenu5:     "お問い合わせ",
    footCtaTitle:  "ご相談・お問い合わせ",
    footHours:     "受付時間 9:00〜17:00（月〜土）\n日祝・年末年始を除く",
    footCopy:      "© 2026 HIKARI CARE — Built by Sutanology",
    footPrivacy:   "プライバシーポリシー",
    footTerms:     "利用規約",

    /* ── SERVICE PAGE ── */
    svcPageEn:     "SERVICE",
    svcPageTitle:  "サービス紹介",
    svcBread:      "サービス紹介",

    svc1DetailTag:   "RESIDENTIAL CARE",
    svc1DetailTitle: "有料老人ホーム",
    svc1DetailDesc:  "24時間365日、専任スタッフが常駐する安心の住まいです。食事・入浴・排泄などの日常生活介助はもちろん、個別に作成したケアプランに基づいた丁寧なサポートを行います。医療機関との連携体制も充実しており、急な体調変化にも迅速に対応できます。",
    svc1dp1: "24時間専任スタッフ常駐・夜間対応体制完備",
    svc1dp2: "栄養士監修の日替わり食事（選択メニュー・特別食対応）",
    svc1dp3: "個別ケアプランに基づく丁寧な生活支援",
    svc1dp4: "協力医療機関との連携による安心の医療体制",
    svc1dp5: "機能訓練・リハビリプログラムの充実",
    svc1dp6: "季節行事・音楽療法・外出レクリエーション",
    svc1dBtn: "見学・資料請求のご相談 →",

    svc2DetailTag:   "DAY SERVICE",
    svc2DetailTitle: "デイサービス（通所介護）",
    svc2DetailDesc:  "自宅から通いながら、日中の活動・機能訓練・入浴などのサービスを受けることができます。ご家族の介護負担を軽減しながら、在宅生活を長く続けていただくためのサービスです。仲間との交流を通じて、生活に活気とリズムをもたらします。",
    svc2dp1: "自宅への送迎サービスあり（エリア指定）",
    svc2dp2: "理学療法士・作業療法士による機能訓練",
    svc2dp3: "入浴・食事・排泄介助をワンストップ提供",
    svc2dp4: "脳トレ・手芸・音楽など多彩なレクリエーション",
    svc2dp5: "ご家族への情報提供・相談対応",
    svc2dBtn: "体験利用のご相談 →",

    svc3DetailTag:   "HOME VISIT CARE",
    svc3DetailTitle: "訪問介護（ホームヘルパー）",
    svc3DetailDesc:  "住み慣れたご自宅で安心して生活を続けていただくために、ヘルパーがご自宅を訪問しサポートします。身体介護から生活援助まで、必要なサービスを組み合わせてご利用いただけます。",
    svc3dp1: "食事・入浴・排泄などの身体介護",
    svc3dp2: "掃除・洗濯・買い物などの生活援助",
    svc3dp3: "ケアマネジャーと連携した個別プラン",
    svc3dp4: "定期訪問から緊急対応まで柔軟に対応",
    svc3dBtn: "ご利用のご相談 →",

    svcCtaEn:    "CONTACT",
    svcCtaTitle: "サービスについてまずはお気軽にご相談ください",
    svcCtaDesc:  "見学・体験利用・資料請求など、どんなご相談でもお受けしています。専門スタッフが丁寧にご案内します。",
    svcCtaBtn1:  "お問い合わせ",
    svcCtaBtn2:  "施設を探す",

    /* ── FACILITY PAGE ── */
    facPageEn:    "FIND A FACILITY",
    facPageTitle: "施設を探す",
    facBread:     "施設を探す",
    facSearchEn:  "SEARCH",
    facSearchTitle:"エリア・サービスから施設を絞り込む",
    facSearchDesc: "ご希望の地域やサービス種別を選択して、最適な施設をお探しください。",
    facRegionLabel:"エリアで絞り込む",
    facSvcLabel:   "サービスで絞り込む",
    facRegAll:     "すべての地域",
    facRegTokyo:   "東京都",
    facRegOsaka:   "大阪府",
    facRegShizuoka:"静岡県",
    facSvcAll:     "すべてのサービス",
    facSvcHome:    "有料老人ホーム",
    facSvcDay:     "デイサービス",
    facSvcCare:    "訪問介護",
    facEmpty:      "条件に合う施設が見つかりませんでした。条件を変えてお試しください。",
    facLink:       "詳細・見学を申込む ›",

    facCtaEn:    "CONTACT",
    facCtaTitle: "施設についてお気軽にご相談ください",
    facCtaDesc:  "見学・体験入居はいつでも受付中。電話でのご相談もお気軽にどうぞ。",
    facCtaBtn1:  "お問い合わせ",
    facCtaBtn2:  "📞 0120-000-000",

    /* ── CONTACT PAGE ── */
    conPageEn:    "CONTACT",
    conPageTitle: "お問い合わせ",
    conBread:     "お問い合わせ",
    conEn:        "GET IN TOUCH",
    conTitle:     "ご相談・お問い合わせ",
    conDesc:      "見学・体験利用・資料請求など、どんなご相談でもお気軽にどうぞ。担当者より3営業日以内にご連絡いたします。",
    conTelLabel:  "お電話",
    conEmailLabel:"メール",
    conAddrLabel: "本社所在地",
    conVisitLabel:"見学対応時間",
    conVisitHours:"10:00〜16:00",
    conVisitNote: "事前予約が必要です",

    /* Form */
    fName:         "お名前",
    fNameKana:     "お名前（ふりがな）",
    fEmail:        "メールアドレス",
    fTel:          "電話番号",
    fType:         "お問い合わせ種別",
    fTypeSelect:   "選択してください",
    fType1:        "施設見学のご予約",
    fType2:        "資料請求",
    fType3:        "サービスに関するご相談",
    fType4:        "費用についてのご相談",
    fType5:        "体験入居・体験利用のご予約",
    fType6:        "採用に関するお問い合わせ",
    fType7:        "その他",
    fMessage:      "お問い合わせ内容",
    fPref:         "ご希望の連絡方法",
    fPref1:        "メールで連絡を希望する",
    fPref2:        "電話で連絡を希望する",
    fPref3:        "どちらでも可",
    fRequired:     "必須",
    fSubmit:       "送信する",
    fSending:      "送信中...",
    fNamePh:       "山田 太郎",
    fNameKanaPh:   "やまだ たろう",
    fEmailPh:      "example@email.com",
    fTelPh:        "000-0000-0000",
    fMsgPh:        "ご質問やご要望をご記入ください。",
    fThanksTitle:  "お問い合わせありがとうございます",
    fThanksDesc:   "内容を確認の上、担当者より3営業日以内にご連絡いたします。しばらくお待ちくださいませ。",

    /* Recruitment */
    recEn:         "RECRUITMENT",
    recTitle:      "採用情報",
    recDesc:       "ひかり苑では、利用者様の笑顔のために共に働くスタッフを積極的に募集しています。",
    recDetailTag:  "JOIN OUR TEAM",
    recDetailTitle:"介護スタッフ・看護スタッフ 募集中",
    recDetailDesc: "「誰かの役に立ちたい」「人と関わる仕事がしたい」そんな想いを持つ方を歓迎します。未経験からスタートした先輩スタッフも多数活躍中。充実した研修制度とキャリアサポートで、あなたの成長を全力でバックアップします。",
    recp1:         "未経験・無資格歓迎（介護福祉士取得支援あり）",
    recp2:         "正社員・パート・派遣など多様な雇用形態",
    recp3:         "充実した研修制度・OJTサポート",
    recp4:         "産育休・時短勤務など制度が整った職場環境",
    recp5:         "スタッフの声を大切にする風通しの良い職場",
    recApplyBtn:   "採用に応募する →",
    recConsultBtn: "採用について相談する",
    recTableTitle: "募集職種・待遇",
    recTh1:        "職種",
    recTh2:        "雇用形態",
    recTh3:        "給与",
    recNote:       "※ 給与は経験・資格・勤務地により異なります。詳しくはお問い合わせください。",
  },

  /* ── ENGLISH ── */
  en: {
    /* Util bar */
    utilTel:     "📞 0120-000-000",
    utilHours:   "Weekdays & Sat 9:00–17:00",
    langToggle:  "日本語",

    /* Navigation */
    navHome:     "Home",
    navService:  "Services",
    navFacility: "Find a Facility",
    navRecruit:  "Careers",
    navContact:  "Contact",

    /* Header CTA */
    telLabel:    "Call us for consultation",
    btnContact:  "Contact Us",

    /* Mobile menu */
    mobileClose: "Close",

    /* ── INDEX ── */
    heroBadge:    "Care With Heart",
    heroTitle1:   "Heartfelt care,",
    heroTitle2:   "right by your side.",
    heroDesc:     "At Hikari-en, we are dedicated to\nsupporting each person to live with\ntheir own rhythm and a bright smile.",
    heroBtnFind:  "Find a Facility",
    heroBtnSvc:   "Our Services",

    /* Gallery */
    galleryEn:    "DAILY LIFE",
    galleryTitle: "Life at Hikari-en",
    galleryDesc:  "A glimpse into the warm daily moments shared by our staff and residents.",
    galCap1:      "Recreation Activities",
    galCap2:      "Seasonal Cherry Blossom Viewing",
    galCap3:      "Rehabilitation & Exercise",
    galCap4:      "Mealtime Together",
    galCap5:      "Relaxing in the Courtyard",

    /* Features */
    featEn:       "FEATURE",
    featTitle:    "3 Hallmarks of Hikari-en",
    featDesc:     "We deliver safe, secure, and warm care to every person in our community.",
    feat1Title:   "Safe & Reliable Care\nby Qualified Professionals",
    feat1Desc:    "Certified care workers and nurses provide round-the-clock support. We are ready for emergencies and maintain strong ties with partner medical institutions.",
    feat2Title:   "Warm & Comfortable\nLiving Environments",
    feat2Desc:    "Our spaces are designed to feel like home — seasonal interior touches and lush garden courtyards provide a peaceful, relaxed daily life for our residents.",
    feat3Title:   "Personalized Support\nfor a Life Full of Smiles",
    feat3Desc:    "We honor each person's hobbies and sense of purpose, creating individual care plans that include music, crafts, and seasonal events to bring joy every day.",

    /* Services preview */
    svcEn:        "SERVICE",
    svcTitle:     "Our Services",
    svcDesc:      "We offer a range of services tailored to the diverse needs of our residents and users.",
    svc1Tag:      "RESIDENTIAL CARE",
    svc1Title:    "Residential Care Home",
    svc1Desc:     "A safe, 24-hour staffed residence for elderly individuals. We provide comprehensive support including meals, bathing, and rehabilitation — all guided by a personalized care plan.",
    svc1p1:       "24/7 dedicated staff on-site, fast emergency response",
    svc1p2:       "Dietitian-supervised daily menus with selectable options",
    svc1p3:       "Personalized care plans for attentive daily support",
    svc1Btn:      "Learn More →",
    svc2Tag:      "DAY SERVICE",
    svc2Title:    "Day Service (Outpatient)",
    svc2Desc:     "Residents can attend during the day for activities, rehabilitation, and bathing services while living at home. We reduce the burden on family caregivers while supporting independent living.",
    svc2p1:       "Door-to-door pickup and drop-off service",
    svc2p2:       "Functional training by physical and occupational therapists",
    svc2p3:       "All-in-one: bathing, meals, and care support",
    svc2Btn:      "Learn More →",

    /* About */
    aboutEn:      "ABOUT US",
    aboutTitle:   "We care for residents\nlike our own family.",
    aboutDesc:    "At Hikari-en, we don't simply provide care — we walk alongside each person's life story, helping them find meaning and joy every day.",
    phil1Title:   "Preserving each person's identity",
    phil1Desc:    "We respect each resident's long-held habits and individuality, creating an environment where they can truly be themselves.",
    phil2Title:   "Cherishing family bonds",
    phil2Desc:    "We collaborate closely with families and aim to be an open facility where loved ones can visit and participate with ease and peace of mind.",
    phil3Title:   "Continuous quality improvement",
    phil3Desc:    "Through staff training and external assessments, we are committed to raising the standard of care every single day.",

    /* News */
    newsEn:        "NEWS",
    newsTitle:     "News & Activity Reports",
    newsDesc:      "Stay up to date with our latest announcements and a look at our daily activities.",
    newsCatEvent:  "Event",
    newsCatRecruit:"Careers",
    newsCatNews:   "Notice",
    news1Date:     "Apr 20, 2026",
    news1Title:    "Spring Cherry Blossom Event Held",
    news1Excerpt:  "Residents and staff enjoyed a beautiful cherry blossom walk at the nearby park. So many smiles were shared!",
    news2Date:     "Apr 5, 2026",
    news2Title:    "Hiring Care Staff — No Experience Required",
    news2Excerpt:  "We are accepting applications for both full-time and part-time positions. Credential support available. Please reach out!",
    news3Date:     "Mar 15, 2026",
    news3Title:    "Tokyo Shinjuku Facility Grand Reopening",
    news3Excerpt:  "Communal spaces and private rooms have been fully renovated. We look forward to welcoming you in a refreshed environment.",
    newsMoreBtn:   "View All News →",

    /* CTA */
    ctaEn:        "FIND CARE",
    ctaTitle:     "Find your nearest\nHikari-en facility",
    ctaDesc:      "Search by region and service type to find the facility that fits your needs. Tours and trial stays are always welcome.",
    ctaBtn1:      "Find a Facility",
    ctaBtn2:      "Request Info / Book a Tour",

    /* Recruitment teaser */
    recruitTag:   "RECRUITMENT",
    recruitTitle: "We're Hiring Care Staff",
    recruitDesc:  "Join our team and help bring smiles to the lives of our residents. Open to all experience levels — we provide full training and credential support.",
    recruitBtn:   "View Careers →",

    /* Footer */
    footDesc:      "Delivering warm, heartfelt care to bring joy and peace of mind to every resident, every day.",
    footMenuTitle: "Menu",
    footMenu1:     "Home",
    footMenu2:     "Services",
    footMenu3:     "Find a Facility",
    footMenu4:     "Careers",
    footMenu5:     "Contact",
    footCtaTitle:  "Contact & Inquiries",
    footHours:     "Mon–Sat 9:00–17:00\nExcl. Sundays & Holidays",
    footCopy:      "© 2026 HIKARI CARE — Built by Sutanology",
    footPrivacy:   "Privacy Policy",
    footTerms:     "Terms of Use",

    /* ── SERVICE PAGE ── */
    svcPageEn:     "SERVICE",
    svcPageTitle:  "Our Services",
    svcBread:      "Services",

    svc1DetailTag:   "RESIDENTIAL CARE",
    svc1DetailTitle: "Residential Care Home",
    svc1DetailDesc:  "A 24/7 staffed residence offering comprehensive support including meals, bathing, and daily care — all based on a personalized care plan. We also have strong partnerships with local medical institutions for prompt response.",
    svc1dp1: "24/7 on-site staff with full overnight coverage",
    svc1dp2: "Dietitian-supervised meals with customizable menu options",
    svc1dp3: "Personalized care plans for attentive daily support",
    svc1dp4: "Coordinated medical care with partner hospitals and clinics",
    svc1dp5: "Functional training and rehabilitation programs",
    svc1dp6: "Seasonal events, music therapy, and community outings",
    svc1dBtn: "Book a Tour or Request Info →",

    svc2DetailTag:   "DAY SERVICE",
    svc2DetailTitle: "Day Service (Outpatient Care)",
    svc2DetailDesc:  "Participants come in during the day for activities, rehabilitation, bathing, and meals while continuing to live at home. Day service helps reduce the burden on family caregivers and supports long-term independent living.",
    svc2dp1: "Door-to-door pickup and drop-off service (select areas)",
    svc2dp2: "Rehabilitation led by physical and occupational therapists",
    svc2dp3: "All-in-one bathing, dining, and care support",
    svc2dp4: "Puzzles, crafts, music therapy, and social recreation",
    svc2dp5: "Regular communication and consultation with families",
    svc2dBtn: "Schedule a Trial Visit →",

    svc3DetailTag:   "HOME VISIT CARE",
    svc3DetailTitle: "Home Visit Care (Home Helper)",
    svc3DetailDesc:  "Our trained care workers visit your home to provide personal care and daily living assistance, helping you remain comfortable and independent in familiar surroundings.",
    svc3dp1: "Personal care: bathing, eating, and hygiene support",
    svc3dp2: "Daily living support: cleaning, laundry, grocery shopping",
    svc3dp3: "Customized service plan developed with your care manager",
    svc3dp4: "Flexible scheduling from regular visits to urgent response",
    svc3dBtn: "Inquire About Home Care →",

    svcCtaEn:    "CONTACT",
    svcCtaTitle: "Have a question? We're happy to help.",
    svcCtaDesc:  "We welcome inquiries about tours, trial stays, or any other services. Our team will guide you with care and expertise.",
    svcCtaBtn1:  "Contact Us",
    svcCtaBtn2:  "Find a Facility",

    /* ── FACILITY PAGE ── */
    facPageEn:    "FIND A FACILITY",
    facPageTitle: "Find a Facility",
    facBread:     "Find a Facility",
    facSearchEn:  "SEARCH",
    facSearchTitle:"Search by Region & Service Type",
    facSearchDesc: "Select your preferred region and type of care to find the right Hikari-en facility for you.",
    facRegionLabel:"Filter by Region",
    facSvcLabel:   "Filter by Service",
    facRegAll:     "All Regions",
    facRegTokyo:   "Tokyo",
    facRegOsaka:   "Osaka",
    facRegShizuoka:"Shizuoka",
    facSvcAll:     "All Services",
    facSvcHome:    "Residential Care Home",
    facSvcDay:     "Day Service",
    facSvcCare:    "Home Visit Care",
    facEmpty:      "No facilities found matching your criteria. Please try different filters.",
    facLink:       "Details & Tours ›",

    facCtaEn:    "CONTACT",
    facCtaTitle: "Questions about a facility? Let's talk.",
    facCtaDesc:  "Tours and trial stays are available anytime. Call or message us — we'll help you find the right fit.",
    facCtaBtn1:  "Contact Us",
    facCtaBtn2:  "📞 0120-000-000",

    /* ── CONTACT PAGE ── */
    conPageEn:    "CONTACT",
    conPageTitle: "Contact Us",
    conBread:     "Contact",
    conEn:        "GET IN TOUCH",
    conTitle:     "Inquiries & Consultation",
    conDesc:      "Whether you'd like to book a tour, request materials, or just ask a question — feel free to reach out. We'll respond within 3 business days.",
    conTelLabel:  "Phone",
    conEmailLabel:"Email",
    conAddrLabel: "Head Office",
    conVisitLabel:"Tour Hours",
    conVisitHours:"10:00–16:00",
    conVisitNote: "Advance reservation required",

    /* Form */
    fName:         "Full Name",
    fNameKana:     "Name (Phonetic)",
    fEmail:        "Email Address",
    fTel:          "Phone Number",
    fType:         "Inquiry Type",
    fTypeSelect:   "Please select",
    fType1:        "Facility Tour Reservation",
    fType2:        "Request Information",
    fType3:        "Service Consultation",
    fType4:        "Cost Consultation",
    fType5:        "Trial Stay / Day Visit",
    fType6:        "Career Inquiry",
    fType7:        "Other",
    fMessage:      "Message",
    fPref:         "Preferred Contact Method",
    fPref1:        "Email preferred",
    fPref2:        "Phone preferred",
    fPref3:        "Either is fine",
    fRequired:     "Required",
    fSubmit:       "Send Message",
    fSending:      "Sending...",
    fNamePh:       "Taro Yamada",
    fNameKanaPh:   "Phonetic reading",
    fEmailPh:      "example@email.com",
    fTelPh:        "000-0000-0000",
    fMsgPh:        "Please describe your question or request.",
    fThanksTitle:  "Thank you for your message",
    fThanksDesc:   "We will review your inquiry and respond within 3 business days. We look forward to speaking with you.",

    /* Recruitment */
    recEn:         "RECRUITMENT",
    recTitle:      "Careers",
    recDesc:       "We are actively looking for compassionate individuals to join our team at Hikari-en.",
    recDetailTag:  "JOIN OUR TEAM",
    recDetailTitle:"Hiring Care & Nursing Staff",
    recDetailDesc: "If you have a heart for helping people, we want to hear from you. Many of our current team members started without experience. We provide comprehensive training, credentials support, and a workplace where your voice is heard.",
    recp1:         "No experience required (certification support available)",
    recp2:         "Full-time, part-time, and contract positions available",
    recp3:         "Thorough on-the-job training and mentoring",
    recp4:         "Family-friendly: parental leave, flexible hours, and more",
    recp5:         "Open, supportive workplace culture that values every team member",
    recApplyBtn:   "Apply Now →",
    recConsultBtn: "Ask About Careers",
    recTableTitle: "Open Positions & Compensation",
    recTh1:        "Position",
    recTh2:        "Type",
    recTh3:        "Compensation",
    recNote:       "* Actual pay varies by experience, qualifications, and location. Please contact us for details.",
  },
};
